import { QuoteEntity } from "../../entities/quote.entity";
import { QuoteItemResponseDto } from "./quote-item-response.dto";

export class QuoteResponseDto {
  constructor(private readonly quote: QuoteEntity) {}

  toJSON() {
    return {
      id: this.quote.id,
      quoteNumber: this.quote.quoteNumber,
      status: this.quote.status,
      deliveryStatus: this.quote.deliveryStatus,
      firstSentAt: this.quote.firstSentAt ? this.quote.firstSentAt.toISOString() : null,
      orderStatus: this.quote.orderStatus,
      orderGeneratedAt: this.quote.orderGeneratedAt ? this.quote.orderGeneratedAt.toISOString() : null,
      orderReference: this.quote.orderReference,
      origin: this.quote.origin,
      captureMethod: this.quote.captureMethod,
      originalQuoteDate: this.quote.originalQuoteDate
        ? this.quote.originalQuoteDate.toISOString().split("T")[0]
        : null,
      sourceChannel: this.quote.sourceChannel,
      currency: this.quote.currency,
      exchangeRate: this.quote.exchangeRate,
      exchangeRateDate: this.quote.exchangeRateDate.toISOString().split("T")[0],
      taxRate: this.quote.taxRate,
      subtotal: this.quote.subtotal,
      tax: this.quote.tax,
      total: this.quote.total,
      deliveryPlace: this.quote.deliveryPlace,
      paymentTerms: this.quote.paymentTerms,
      validityDays: this.quote.validityDays,
      validUntil: this.quote.validUntil.toISOString().split("T")[0],
      branchId: this.quote.branchId,
      customerId: this.quote.customerId,
      createdByUserId: this.quote.createdByUserId,
      updatedByUserId: this.quote.updatedByUserId,
      providedByUserId: this.quote.providedByUserId,
      providedByNameSnapshot: this.quote.providedByNameSnapshot,
      providedByBranchNameSnapshot: this.quote.providedByBranchNameSnapshot,
      providedAt: this.quote.providedAt ? this.quote.providedAt.toISOString() : null,
      providedByAssignedByUserId: this.quote.providedByAssignedByUserId,
      rejectionReason: this.quote.rejectionReason,
      rejectionComment: this.quote.rejectionComment,
      rejectedAt: this.quote.rejectedAt ? this.quote.rejectedAt.toISOString() : null,
      rejectedByUserId: this.quote.rejectedByUserId,
      rejectedByUser: this.quote.rejectedByUser,
      cancellationReason: this.quote.cancellationReason,
      cancellationComment: this.quote.cancellationComment,
      cancelledAt: this.quote.cancelledAt ? this.quote.cancelledAt.toISOString() : null,
      cancelledByUserId: this.quote.cancelledByUserId,
      cancelledByUser: this.quote.cancelledByUser,
      approvalReturnReason: this.quote.approvalReturnReason,
      approvalReturnComment: this.quote.approvalReturnComment,
      rootQuoteId: this.quote.rootQuoteId,
      previousVersionId: this.quote.previousVersionId,
      supersededByQuoteId: this.quote.supersededByQuoteId,
      revisionNumber: this.quote.revisionNumber,
      revisionReason: this.quote.revisionReason,
      revisionComment: this.quote.revisionComment,
      supersededAt: this.quote.supersededAt ? this.quote.supersededAt.toISOString() : null,
      archivedAt: this.quote.archivedAt ? this.quote.archivedAt.toISOString() : null,
      archivedByUserId: this.quote.archivedByUserId,
      archivedByUser: this.quote.archivedByUser,
      archiveReason: this.quote.archiveReason,
      nextRevision: this.quote.nextRevision,
      notes: this.quote.notes,
      createdAt: this.quote.createdAt.toISOString(),
      updatedAt: this.quote.updatedAt.toISOString(),
      branch: this.quote.branch,
      customer: this.quote.customer,
      createdByUser: this.quote.createdByUser,
      updatedByUser: this.quote.updatedByUser,
      items: this.quote.items.map((item) => new QuoteItemResponseDto(item).toJSON()),
      events: this.quote.events.map((event) => ({
        id: event.id,
        quoteId: event.quoteId,
        status: event.status,
        note: event.note,
        actorUserId: event.actorUserId,
        createdAt: event.createdAt.toISOString(),
        actorUser: event.actorUser,
      })),
    };
  }
}
