import { QuoteItemEntity } from "../../entities/quote-item.entity";

export class QuoteItemResponseDto {
  constructor(private readonly item: QuoteItemEntity) {}

  toJSON() {
    return {
      id: this.item.id,
      quoteId: this.item.quoteId,
      clientItemId: this.item.clientItemId,
      productId: this.item.productId,
      externalProductCode: this.item.externalProductCode,
      ean: this.item.ean,
      customerDescription: this.item.customerDescription,
      customerDescriptionOriginal: this.item.customerDescriptionOriginal,
      customerDescriptionEditedAt: this.item.customerDescriptionEditedAt?.toISOString() ?? null,
      customerDescriptionEditedByUserId: this.item.customerDescriptionEditedByUserId,
      customerDescriptionEditedByUser: this.item.customerDescriptionEditedByUser,
      customerUnit: this.item.customerUnit,
      erpDescription: this.item.erpDescription,
      unit: this.item.unit,
      qty: this.item.qty,
      stock: this.item.stock,
      deliveryTime: this.item.deliveryTime,
      itemComment: this.item.itemComment,
      sellerSupplierId: this.item.sellerSupplierId,
      sellerSupplierNameSnapshot: this.item.sellerSupplierNameSnapshot,
      sellerQuotedUnitCost: this.item.sellerQuotedUnitCost,
      sellerQuotedCurrency: this.item.sellerQuotedCurrency,
      sellerQuotedExchangeRate: this.item.sellerQuotedExchangeRate,
      sellerQuotedBrand: this.item.sellerQuotedBrand,
      sellerSupplierDescription: this.item.sellerSupplierDescription,
      sellerSupplierOrigin: this.item.sellerSupplierOrigin,
      sellerSupplierQuoteValidUntil: this.item.sellerSupplierQuoteValidUntil,
      sellerSupplierQuoteReference: this.item.sellerSupplierQuoteReference,
      sellerSupplierQuoteNotes: this.item.sellerSupplierQuoteNotes,
      sellerOriginRestrictions: this.item.sellerOriginRestrictions,
      sellerDeliveryState: this.item.sellerDeliveryState,
      sellerSupplierDeliveryTime: this.item.sellerSupplierDeliveryTime,
      purchaseStandard: this.item.purchaseStandard,
      purchaseDiameter: this.item.purchaseDiameter,
      purchaseThickness: this.item.purchaseThickness,
      purchaseBore: this.item.purchaseBore,
      technicalFamily: this.item.technicalFamily,
      technicalAttributes: this.item.technicalAttributes,
      cost: this.item.cost,
      costCurrency: this.item.costCurrency,
      erpSaleCurrency: this.item.erpSaleCurrency,
      marginPct: this.item.marginPct,
      effectiveCostAtQuote: this.item.effectiveCostAtQuote,
      isBelowEffectiveCost: this.item.isBelowEffectiveCost,
      effectiveCostVariance: this.item.effectiveCostVariance,
      effectiveCostVariancePct: this.item.effectiveCostVariancePct,
      effectiveCostEvaluatedAt: this.item.effectiveCostEvaluatedAt?.toISOString() ?? null,
      effectiveCostEvaluatedByUserId: this.item.effectiveCostEvaluatedByUserId,
      effectiveCostEvaluatedByUser: this.item.effectiveCostEvaluatedByUser,
      sourceCurrency: this.item.sourceCurrency,
      sourceUnitPrice: this.item.sourceUnitPrice,
      sourceSubtotal: this.item.sourceSubtotal,
      unitPrice: this.item.unitPrice,
      subtotal: this.item.subtotal,
      sourceRequiresReview: this.item.sourceRequiresReview,
      requiresReview: this.item.requiresReview,
      createdAt: this.item.createdAt.toISOString(),
      updatedAt: this.item.updatedAt.toISOString(),
      product: this.item.product,
    };
  }
}
