ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CREDIT_COLLECTIONS';
ALTER TYPE "WhatsAppInternalAlertType" ADD VALUE IF NOT EXISTS 'CUSTOMER_ONBOARDING_PENDING';
ALTER TYPE "WhatsAppInternalAlertType" ADD VALUE IF NOT EXISTS 'CUSTOMER_ONBOARDING_CORRECTION';
ALTER TYPE "WhatsAppInternalAlertType" ADD VALUE IF NOT EXISTS 'CUSTOMER_ONBOARDING_ERP_LINKED';

ALTER TABLE "customer_onboardings"
  ADD COLUMN IF NOT EXISTS "review_note" VARCHAR(1000);
