@baseUrl = http://localhost:4600/api
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYWY2ZmY4Yy0wMGUyLTRlMzMtYTAwZC1lMTY2NDU5NWVjMjQiLCJyb2xlIjoiQURNSU4iLCJicmFuY2hJZCI6IjNhYTRkNjY2LTY2NmEtNDBmZi1hOGI5LTM2NzU2NTg1YTBkZCIsImVycFVzZXJDb2RlIjpudWxsLCJpYXQiOjE3NzI3NDQwNzksImV4cCI6MTc3Mjc3Mjg3OX0.PpamD9P93EJc1VPmIConYOv9xo2jRq0eCfmW360FVK8

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@tuvansa.com",
  "password": "Tuvansa123!"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@tuvansa.com",
  "password": "Tuvansa123!"
}

### Me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{jwt}}
